CREATE DATABASE M151

CREATE TABLE tw_Transfers (
	TransferId INT NOT NULL PRIMARY KEY,
	PlayerId INT NOT NULL,
	OldTeamId INT NOT NULL,
	NewTeamId INT NOT NULL,
	TransferSum FLOAT NOT NULL,
	Wage FLOAT NOT NULL
)

CREATE TABLE tw_Players (
	PlayerId INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	PlayerName VARCHAR(255) NOT NULL,
	PlayerAge INT NOT NULL,
	PlayerNationality VARCHAR(50) NOT NULL,
	PlayerPosition VARCHAR(50) NOT NULL
)

CREATE TABLE tw_Teams (
	TeamId INT NOT NULL PRIMARY KEY IDENTITY(1,1),
	TeamName VARCHAR(255) NOT NULL,
	TeamLeague VARCHAR(255) NOT NULL,
)