CREATE DATABASE M151

CREATE TABLE tw_Transfers (
	TransferId INT NOT NULL PRIMARY KEY,
	PlayerId INT NOT NULL,
	OldTeamId INT NOT NULL,
	NewTeamId INT NOT NULL,
	TransferSum FLOAT NOT NULL,
	Wage FLOAT NOT NULL
)

CREATE TABLE tw_Players (
	PlayerId INT NOT NULL PRIMARY KEY,
)